version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: akademia_postgres
    restart: always
    environment:
      POSTGRES_USER: akademia_admin
      POSTGRES_PASSWORD: akademia_123
      POSTGRES_DB: akademia_cms
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
